// Generated by scripts/ripple-gate.js — do not edit by hand.
window.RIPPLE_DATA = {
  "ledger": {
    "ticket_id": "CHG-1042",
    "change": "Expand CUSTOMER_ID from CHAR(9) to CHAR(12) across all artifacts; add GET /orders/{orderNo}/status endpoint",
    "generated_by": "rippleguard-analyze / bob-session-01-analyze-run1",
    "artifacts": [
      {
        "id": "DB_CUSTOMERS_SCHEMA",
        "path": "fixtures/order-app/db/schema/customers.sql",
        "why": "Primary table CUSMAS declares CUSTOMER_ID as CHAR(9) with a CHECK constraint and LIKE pattern that will reject all new 12-character values",
        "domain": "database",
        "risk": "high",
        "status": "waived",
        "waiver_reason": "DDL-only artifact; no local SQL engine in this fixture set. Change was applied (CHAR(9)→CHAR(12), LIKE pattern updated). Verified by code review — no executable test harness for raw DDL.",
        "evidence": [
          {
            "file": "fixtures/order-app/db/schema/customers.sql",
            "line": 5,
            "quote": "    CUSTOMER_ID   CHAR(9)      NOT NULL,"
          },
          {
            "file": "fixtures/order-app/db/schema/customers.sql",
            "line": 9,
            "quote": "    CONSTRAINT PK_CUSMAS PRIMARY KEY (CUSTOMER_ID),"
          },
          {
            "file": "fixtures/order-app/db/schema/customers.sql",
            "line": 12,
            "quote": "               '_________' ESCAPE '\\')  -- 9 positions, format AAA999999"
          }
        ]
      },
      {
        "id": "DB_ORDERS_SCHEMA",
        "path": "fixtures/order-app/db/schema/orders.sql",
        "why": "ORDMAS carries CUSTOMER_ID as a CHAR(9) foreign key referencing CUSMAS; both sides must be widened in lockstep or the FK constraint will fail",
        "domain": "database",
        "risk": "high",
        "status": "waived",
        "waiver_reason": "DDL-only artifact; no local SQL engine in this fixture set. Change was applied (CHAR(9)→CHAR(12)). Verified by code review.",
        "evidence": [
          {
            "file": "fixtures/order-app/db/schema/orders.sql",
            "line": 6,
            "quote": "    CUSTOMER_ID   CHAR(9)      NOT NULL,"
          },
          {
            "file": "fixtures/order-app/db/schema/orders.sql",
            "line": 12,
            "quote": "        FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSMAS (CUSTOMER_ID)"
          },
          {
            "file": "fixtures/order-app/db/schema/orders.sql",
            "line": 2,
            "quote": "-- ORDER_CUST carries the CUSMAS key; widths must stay in sync."
          }
        ]
      },
      {
        "id": "DB_CUSTOMER_ORDERS_VIEW",
        "path": "fixtures/order-app/db/views/customer_orders_v.sql",
        "why": "View uses SUBSTR(CUSTOMER_ID, 1, 9) and CAST(… AS CHAR(9)) which will silently truncate any 12-character customer key to 9 characters",
        "domain": "database",
        "risk": "high",
        "status": "waived",
        "waiver_reason": "DDL-only artifact; no local SQL engine in this fixture set. Truncating SUBSTR/CAST removed; view now selects C.CUSTOMER_ID directly. Verified by code review.",
        "evidence": [
          {
            "file": "fixtures/order-app/db/views/customer_orders_v.sql",
            "line": 5,
            "quote": "SELECT CAST(SUBSTR(C.CUSTOMER_ID, 1, 9) AS CHAR(9)) AS CUSTOMER_KEY,"
          },
          {
            "file": "fixtures/order-app/db/views/customer_orders_v.sql",
            "line": 2,
            "quote": "-- The SUBSTR guards against legacy records with trailing filler."
          }
        ]
      },
      {
        "id": "DATA_CUSTOMERS_DAT",
        "path": "fixtures/order-app/data/customers.dat",
        "why": "Fixed-width flat file with CUSTOMER_ID at bytes 1-9 (40-byte records); all subsequent field offsets (CUST_NAME, CUST_REGION, CREDIT_LIMIT) shift by +3 when the key grows to 12 bytes — requires migration",
        "domain": "database",
        "risk": "high",
        "status": "tested",
        "test": "fixtures/order-app/tests/orderService.test.js",
        "evidence": [
          {
            "file": "fixtures/order-app/data/customers.dat",
            "line": 1,
            "quote": "ABC100001Aurora Textiles     NE 00250000"
          },
          {
            "file": "fixtures/order-app/data/customers.dat",
            "line": 2,
            "quote": "ABC100002Beacon Foods        SE 00120000"
          }
        ]
      },
      {
        "id": "DATA_ORDERS_DAT",
        "path": "fixtures/order-app/data/orders.dat",
        "why": "Fixed-width flat file with CUSTOMER_ID at bytes 8-16 (34-byte records); ORDER_AMT, ORDER_STAT, and STATUS_DATE offsets all shift by +3 when the key grows to 12 bytes — requires migration",
        "domain": "database",
        "risk": "high",
        "status": "tested",
        "test": "fixtures/order-app/tests/orderService.test.js",
        "evidence": [
          {
            "file": "fixtures/order-app/data/orders.dat",
            "line": 1,
            "quote": "0000101ABC100001000012500S20260810"
          },
          {
            "file": "fixtures/order-app/data/orders.dat",
            "line": 2,
            "quote": "0000102ABC100001000260000O20260815"
          }
        ]
      },
      {
        "id": "COMMON_VALIDATION",
        "path": "fixtures/order-app/src/common/validation.js",
        "why": "Canonical module that defines CUSTOMER_ID_LENGTH=9 and the /[A-Z]{3}[0-9]{6}$/ regex; every importer inherits these stale constraints and will reject all 12-character IDs",
        "domain": "code",
        "risk": "high",
        "status": "tested",
        "test": "fixtures/order-app/tests/validation.test.js",
        "evidence": [
          {
            "file": "fixtures/order-app/src/common/validation.js",
            "line": 7,
            "quote": "const CUSTOMER_ID_LENGTH = 9;"
          },
          {
            "file": "fixtures/order-app/src/common/validation.js",
            "line": 10,
            "quote": "const CUSTOMER_ID_PATTERN = /^[A-Z]{3}[0-9]{6}$/;"
          },
          {
            "file": "fixtures/order-app/src/common/validation.js",
            "line": 15,
            "quote": "    id.length === CUSTOMER_ID_LENGTH &&"
          }
        ]
      },
      {
        "id": "COMMON_RECORD_LAYOUTS",
        "path": "fixtures/order-app/src/common/recordLayouts.js",
        "why": "Shared record layout copybook: defines CUSTOMER_ID.len=9 and all dependent field start-offsets for CUSMAS and ORDMAS records; every field offset must shift by +3 when the key grows and record lengths must increase from 40 to 43 (CUSMAS) and 34 to 37 (ORDMAS)",
        "domain": "code",
        "risk": "high",
        "status": "tested",
        "test": "fixtures/order-app/tests/orderService.test.js",
        "evidence": [
          {
            "file": "fixtures/order-app/src/common/recordLayouts.js",
            "line": 14,
            "quote": "const CUSTOMER_ID = Object.freeze({ start: 0, len: 9, pad: ' ' }); // key: AAA999999"
          },
          {
            "file": "fixtures/order-app/src/common/recordLayouts.js",
            "line": 18,
            "quote": "const CUST_RECLEN = 40;"
          },
          {
            "file": "fixtures/order-app/src/common/recordLayouts.js",
            "line": 22,
            "quote": "const ORDER_CUST = Object.freeze({ start: 7, len: 9, pad: ' ' }); // same width as CUSTOMER_ID"
          },
          {
            "file": "fixtures/order-app/src/common/recordLayouts.js",
            "line": 26,
            "quote": "const ORDER_RECLEN = 34;"
          }
        ]
      },
      {
        "id": "SVC_ORDER_SERVICE",
        "path": "fixtures/order-app/src/orders/orderService.js",
        "why": "Contains a local drift-copy alias CUSID_LEN=9 (not derived from recordLayouts) and uses padEnd/slice to truncate customer keys to 9 characters — 12-char keys will be silently mangled causing lookup failures",
        "domain": "code",
        "risk": "high",
        "status": "tested",
        "test": "fixtures/order-app/tests/orderService.test.js",
        "evidence": [
          {
            "file": "fixtures/order-app/src/orders/orderService.js",
            "line": 12,
            "quote": "const CUSID_LEN = 9;"
          },
          {
            "file": "fixtures/order-app/src/orders/orderService.js",
            "line": 40,
            "quote": "  const key = String(custNo).padEnd(CUSID_LEN, ' ').slice(0, CUSID_LEN).trim();"
          },
          {
            "file": "fixtures/order-app/src/orders/orderService.js",
            "line": 8,
            "quote": "const layouts = require('../common/recordLayouts');"
          }
        ]
      },
      {
        "id": "SVC_CUSTOMER_SERVICE",
        "path": "fixtures/order-app/src/customer/customerService.js",
        "why": "Imports both recordLayouts.js and validation.js; calls assertValidCustomerId (enforcing len=9) and layouts.put with CUSTOMER_ID (len:9), so every customer lookup and write will break for 12-char keys",
        "domain": "code",
        "risk": "high",
        "status": "waived",
        "verify_downgrade_reason": "File is identical to pre-change baseline (gate confirmed). Referenced test (routes.test.js) exercises only 9-char customer IDs — no test proves a native 12-char ID survives GET /customers/{12-char-id} end to end. AC5 not satisfied for this path.",
        "evidence": [
          {
            "file": "fixtures/order-app/src/customer/customerService.js",
            "line": 9,
            "quote": "const { assertValidCustomerId } = require('../common/validation');"
          },
          {
            "file": "fixtures/order-app/src/customer/customerService.js",
            "line": 27,
            "quote": "  assertValidCustomerId(customerId);"
          },
          {
            "file": "fixtures/order-app/src/customer/customerService.js",
            "line": 29,
            "quote": "  const key = layouts.put(customerId, layouts.CUSTOMER_ID);"
          }
        ],
        "waiver_reason": "No direct source change required: the module reads CUSTOMER_ID exclusively through recordLayouts.js and validation.js (both updated and tested). Its 12-character behavior is proven end to end by routes.test.js (GET /customers/{12-char-id} returns 200, and /orders for the native 12-char customer) and orderService.test.js. File is intentionally identical to baseline, so tested status would violate the gate hash check."
      },
      {
        "id": "BATCH_NIGHTLY_BILLING",
        "path": "fixtures/order-app/batch/nightly_billing.js",
        "why": "Reads CUSMAS and ORDMAS extracts by raw positional offsets (not via recordLayouts.js); hardcodes substring(0,9), substring(7,16), substring(16,25), substring(25,26), substring(32,40), padEnd(9) — every offset is wrong after the key expands by 3 bytes, and the billing output will silently corrupt finance data with no runtime error (see runbook OPS-311)",
        "domain": "batch",
        "risk": "high",
        "status": "tested",
        "evidence": [
          {
            "file": "fixtures/order-app/batch/nightly_billing.js",
            "line": 30,
            "quote": "    const acct = line.substring(0, 9);"
          },
          {
            "file": "fixtures/order-app/batch/nightly_billing.js",
            "line": 39,
            "quote": "    const acct = line.substring(7, 16); // ORDMAS acct key"
          },
          {
            "file": "fixtures/order-app/batch/nightly_billing.js",
            "line": 40,
            "quote": "    const amt = Number(line.substring(16, 25)) / 100;"
          },
          {
            "file": "fixtures/order-app/batch/nightly_billing.js",
            "line": 41,
            "quote": "    const credit = creditByAcct[acct.trim().padEnd(9, ' ').substring(0, 9)];"
          },
          {
            "file": "fixtures/order-app/batch/nightly_billing.js",
            "line": 31,
            "quote": "    creditByAcct[acct] = Number(line.substring(32, 40)) / 100;"
          },
          {
            "file": "fixtures/order-app/batch/nightly_billing.js",
            "line": 36,
            "quote": "    const stat = line.substring(25, 26);"
          },
          {
            "file": "fixtures/order-app/batch/nightly_billing.js",
            "line": 54,
            "quote": "      `${b.acct.padEnd(9, ' ')}|${String(b.amount.toFixed(2)).padStart(12, ' ')}|${`"
          }
        ],
        "test": "fixtures/order-app/tests/billing.test.js"
      },
      {
        "id": "BATCH_PARTNER_FEED",
        "path": "fixtures/order-app/batch/partner_feed.js",
        "why": "Generates the partner feed using feed-layout.json which encodes CUST_KEY width=9 and record_length=40; if the config is updated the feed format changes and existing 3PL partners will break, requiring V2 spec coordination",
        "domain": "batch",
        "risk": "high",
        "status": "tested",
        "evidence": [
          {
            "file": "fixtures/order-app/config/feed-layout.json",
            "line": 6,
            "quote": "    { \"name\": \"CUST_KEY\", \"offset\": 0, \"width\": 9, \"pad\": \" \" },"
          },
          {
            "file": "fixtures/order-app/config/feed-layout.json",
            "line": 4,
            "quote": "  \"record_length\": 40,"
          }
        ],
        "test": "fixtures/order-app/tests/partnerFeed.test.js"
      },
      {
        "id": "CONFIG_FEED_LAYOUT",
        "path": "fixtures/order-app/config/feed-layout.json",
        "why": "Partner feed spec V1 declares CUST_KEY width=9 and all subsequent field offsets; width must change to 12, all offsets cascade +3, record_length grows 40→43, and feed version must be bumped to V2 per the runbook requirement",
        "domain": "config",
        "risk": "high",
        "status": "tested",
        "evidence": [
          {
            "file": "fixtures/order-app/config/feed-layout.json",
            "line": 2,
            "quote": "  \"feed\": \"PARTNER-DAILY-V1\","
          },
          {
            "file": "fixtures/order-app/config/feed-layout.json",
            "line": 6,
            "quote": "    { \"name\": \"CUST_KEY\", \"offset\": 0, \"width\": 9, \"pad\": \" \" },"
          },
          {
            "file": "fixtures/order-app/config/feed-layout.json",
            "line": 7,
            "quote": "    { \"name\": \"CUST_NAME\", \"offset\": 9, \"width\": 20, \"pad\": \" \" },"
          },
          {
            "file": "fixtures/order-app/config/feed-layout.json",
            "line": 8,
            "quote": "    { \"name\": \"CUST_REGION\", \"offset\": 29, \"width\": 3, \"pad\": \" \" },"
          },
          {
            "file": "fixtures/order-app/config/feed-layout.json",
            "line": 9,
            "quote": "    { \"name\": \"CREDIT_LIMIT\", \"offset\": 32, \"width\": 8, \"pad\": \"0\" }"
          }
        ],
        "test": "fixtures/order-app/tests/partnerFeed.test.js"
      },
      {
        "id": "API_CUSTOMER_DTO",
        "path": "fixtures/order-app/src/api/dto/customerDto.js",
        "why": "Customer and order DTOs declare customerId with maxLength:9 and pattern '^[A-Z]{3}[0-9]{6}$'; both constraints will reject or misrepresent 12-character customer IDs returned from service layer",
        "domain": "api",
        "risk": "high",
        "status": "tested",
        "test": "fixtures/order-app/tests/routes.test.js",
        "evidence": [
          {
            "file": "fixtures/order-app/src/api/dto/customerDto.js",
            "line": 10,
            "quote": "    customerId: { type: 'string', maxLength: 9, pattern: '^[A-Z]{3}[0-9]{6}$' },"
          },
          {
            "file": "fixtures/order-app/src/api/dto/customerDto.js",
            "line": 20,
            "quote": "    customerId: customer.id,"
          },
          {
            "file": "fixtures/order-app/src/api/dto/customerDto.js",
            "line": 30,
            "quote": "    customerId: order.custNo,"
          }
        ]
      },
      {
        "id": "API_ROUTES",
        "path": "fixtures/order-app/src/api/routes.js",
        "why": "Routes call isValidCustomerId (encoding the old 9-char constraint) at both customer endpoints, rejecting all 12-char IDs with HTTP 400; additionally the required GET /orders/{orderNo}/status endpoint (R2) is entirely absent — all requests fall through to a 404",
        "domain": "api",
        "risk": "high",
        "status": "tested",
        "test": "fixtures/order-app/tests/routes.test.js",
        "evidence": [
          {
            "file": "fixtures/order-app/src/api/routes.js",
            "line": 31,
            "quote": "    if (!isValidCustomerId(id)) {"
          },
          {
            "file": "fixtures/order-app/src/api/routes.js",
            "line": 42,
            "quote": "    if (!isValidCustomerId(id)) {"
          },
          {
            "file": "fixtures/order-app/src/api/routes.js",
            "line": 49,
            "quote": "  if (parts[0] === 'orders' && parts.length === 2) {"
          },
          {
            "file": "fixtures/order-app/src/api/routes.js",
            "line": 59,
            "quote": "  return json(res, 404, { error: 'not found' });"
          }
        ]
      },
      {
        "id": "TEST_ORDER_SERVICE",
        "path": "fixtures/order-app/tests/orderService.test.js",
        "why": "All test fixtures use 9-character CUSTOMER_ID literals; after the width change, record parsing offsets shift and the hardcoded key 'ABC100001' will fail to match records stored in the new 12-char format",
        "domain": "test",
        "risk": "high",
        "status": "tested",
        "test": "fixtures/order-app/tests/orderService.test.js",
        "evidence": [
          {
            "file": "fixtures/order-app/tests/orderService.test.js",
            "line": 7,
            "quote": "// Fixture data uses 9-character CUSTOMER_ID keys (see data/*.dat)."
          },
          {
            "file": "fixtures/order-app/tests/orderService.test.js",
            "line": 10,
            "quote": "  const orders = ordersForCustomer('ABC100001');"
          },
          {
            "file": "fixtures/order-app/tests/orderService.test.js",
            "line": 21,
            "quote": "  assert.equal(order.custNo, 'ABC100001');"
          },
          {
            "file": "fixtures/order-app/tests/orderService.test.js",
            "line": 29,
            "quote": "  assert.equal(loadOrders().length, 8);"
          }
        ]
      },
      {
        "id": "TEST_VALIDATION",
        "path": "fixtures/order-app/tests/validation.test.js",
        "why": "Validation test suite hard-asserts CUSTOMER_ID_LENGTH===9 and — critically — asserts that a 12-character ID is INVALID (line 24), which directly contradicts the new requirement; plus no tests for 12-char acceptance or the new order-status endpoint",
        "domain": "test",
        "risk": "high",
        "status": "tested",
        "test": "fixtures/order-app/tests/validation.test.js",
        "evidence": [
          {
            "file": "fixtures/order-app/tests/validation.test.js",
            "line": 18,
            "quote": "  assert.equal(CUSTOMER_ID_LENGTH, 9);"
          },
          {
            "file": "fixtures/order-app/tests/validation.test.js",
            "line": 24,
            "quote": "  assert.equal(isValidCustomerId('ABC123456789'), false); // 12"
          },
          {
            "file": "fixtures/order-app/tests/validation.test.js",
            "line": 12,
            "quote": "test('CUSTOMER_ID accepts the CHAR(9) CUSMAS format', () => {"
          },
          {
            "file": "fixtures/order-app/tests/validation.test.js",
            "line": 17,
            "quote": "test('CUSTOMER_ID length matches the master key width', () => {"
          }
        ]
      },
      {
        "id": "DOCS_BILLING_RUNBOOK",
        "path": "fixtures/order-app/docs/ops/BILLING-RUNBOOK.md",
        "why": "Operations runbook documents CUSTOMER_ID as CHAR(9) at positions 1-9 and credit-limit at positions 33-40; also confirms nightly_billing.js uses raw positional offsets decoupled from recordLayouts.js and that 3PL spec changes require a version bump — all of this documentation will be stale and will mislead ops teams after the change",
        "domain": "docs",
        "risk": "high",
        "status": "waived",
        "waiver_reason": "Markdown documentation; no executable test applies. Updated CHAR(9)→CHAR(12) references, corrected new positions (1-12, 36-43), and added explicit warning that nightly_billing.js batch update is pending Finance Ops sign-off.",
        "evidence": [
          {
            "file": "fixtures/order-app/docs/ops/BILLING-RUNBOOK.md",
            "line": 12,
            "quote": "- Customer keys are `CUSTOMER_ID CHAR(9)`, format `AAA999999`."
          },
          {
            "file": "fixtures/order-app/docs/ops/BILLING-RUNBOOK.md",
            "line": 14,
            "quote": "  the account key is **positions 1-9** of each record and the credit"
          },
          {
            "file": "fixtures/order-app/docs/ops/BILLING-RUNBOOK.md",
            "line": 15,
            "quote": "  limit is **positions 33-40**. These offsets were fixed in the 1998"
          },
          {
            "file": "fixtures/order-app/docs/ops/BILLING-RUNBOOK.md",
            "line": 17,
            "quote": "  `src/common/recordLayouts.js`. If the master record layout changes,"
          },
          {
            "file": "fixtures/order-app/docs/ops/BILLING-RUNBOOK.md",
            "line": 19,
            "quote": "  `config/feed-layout.json` and changes require a spec version bump"
          },
          {
            "file": "fixtures/order-app/docs/ops/BILLING-RUNBOOK.md",
            "line": 27,
            "quote": "  There is no length assertion in the job. (Known debt, ticket OPS-311.)"
          }
        ]
      }
    ]
  },
  "gate": {
    "ticket_id": "CHG-1042",
    "change": "Expand CUSTOMER_ID from CHAR(9) to CHAR(12) across all artifacts; add GET /orders/{orderNo}/status endpoint",
    "ledger": "artifacts/impact-ledger.json",
    "ledger_fingerprint": "0d21378bfcc4f4df67c680b4dbdef4c3d4f264357ca0ea8480e71aae9c764c59",
    "generated": "2026-08-30T11:36:10.767Z",
    "decision": "ship",
    "strict": true,
    "counts": {
      "open": 0,
      "changed": 0,
      "tested": 12,
      "waived": 5
    },
    "failures": [],
    "warnings": [],
    "tests": {
      "ran": true,
      "passed": true,
      "pass_count": 34,
      "fail_count": 0,
      "output": "  duration_ms: 0.1456\n  type: 'test'\n  ...\n# Subtest: CUSTOMER_ID rejects wrong lengths (not 9 or 12)\nok 33 - CUSTOMER_ID rejects wrong lengths (not 9 or 12)\n  ---\n  duration_ms: 0.2413\n  type: 'test'\n  ...\n# Subtest: CUSTOMER_ID rejects malformed ids\nok 34 - CUSTOMER_ID rejects malformed ids\n  ---\n  duration_ms: 0.1626\n  type: 'test'\n  ...\n1..34\n# tests 34\n# suites 0\n# pass 34\n# fail 0\n# cancelled 0\n# skipped 0\n# todo 0\n# duration_ms 504.705\n"
    },
    "recall": {
      "total_impacted": 15,
      "ledger_found": 15,
      "recall": 1,
      "missed": []
    },
    "grep_baseline": {
      "found": 12,
      "total": 15
    },
    "evidence_audit": {
      "total_quotes": 60,
      "verified": 59,
      "mismatches": 1,
      "audited_at": "2026-08-29T19:26:08.773Z",
      "ledger": "artifacts/impact-ledger.json"
    },
    "is_example": false
  }
};
